version: '3'
services:
  call-center:
    build: ./callcenter-api
    links:
      - postgres
    image: node:10.9
    ports:
      - "4000:4000"
    volumes:
      - ./callcenter-api:/project
    working_dir: /project
    command:
      - /bin/bash
      - -c
      - rm -rf node_modules && yarn install --production && yarn start
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=teravoz
    ports:
      - 5432:5432
  call-center-front:
    command: bash -c 'yarn && yarn start'
    build: ./callcenter-front
    volumes:
      - ./callcenter-front:/project
    ports:
      - 3000:3000

